<h1 align ='center'> Categorical Data Encoding</h1>

__Categorical Variable:__
- Nomial <code>One hot Encoding</code>
- Ordinal <code>Ordinal encoding</code>

- For ordinal data for independent variable x we use oridinal incodeing 
- but for output variable we use __lebel encoding__

### <font color= #CD5C5C> __Ordinal Encoding__ </font>

#### Import Libraries

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df= pd.read_csv('customer.csv')

In [4]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [5]:
df['education'].value_counts()

PG        18
School    16
UG        16
Name: education, dtype: int64

In [8]:
df= df.iloc[:,2:]

In [9]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

### train test split

In [10]:
from sklearn.model_selection import train_test_split

In [13]:
X=df.drop('purchased', axis=1)
X.head()

review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG

In [15]:
y=df['purchased']
y.head()

0    No
1    No
2    No
3    No
4    No
Name: purchased, dtype: object

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [19]:
X_train.shape, X_test.shape

((40, 2), (10, 2))

### Ordinal Encoding

In [20]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
X_train['review'].value_counts()

Poor       14
Good       13
Average    13
Name: review, dtype: int64

In [23]:
X_train['education'].value_counts()

PG        14
School    13
UG        13
Name: education, dtype: int64

In [24]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'], ['School','UG','PG']])

In [25]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [28]:
X_train= oe.transform(X_train)


C:\Users\Amruta\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [29]:
X_train

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [30]:
X_test = oe.transform(X_test)

In [31]:
X_test

array([[0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.]])

In [32]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

### Label Encoding for Output column

In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
le = LabelEncoder()

In [35]:
le.fit(y_train)

LabelEncoder()

In [36]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [38]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [39]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [40]:
df.head(5)

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No